name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: ap-southeast-2
  ECR_REGISTRY: 058264298011.dkr.ecr.ap-southeast-2.amazonaws.com
  ECR_REPOSITORY: cognitive-creators
  EC2_HOST: 13.210.172.73
  EC2_USER: ubuntu

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push images to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:api-$IMAGE_TAG -f Dockerfile.multi --target api-build .
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:client-$IMAGE_TAG -f Dockerfile.multi --target prod-stage .
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:rag-api-$IMAGE_TAG -f Dockerfile.rag .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:api-$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:client-$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:rag-api-$IMAGE_TAG

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        SSL_CERT: ${{ secrets.SSL_CERT }}
        SSL_KEY: ${{ secrets.SSL_KEY }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        scp -o StrictHostKeyChecking=no -i private_key docker-compose.yml ${EC2_USER}@${EC2_HOST}:~/docker-compose.yml
        ssh -o StrictHostKeyChecking=no -i private_key ${EC2_USER}@${EC2_HOST} << EOF
          export ECR_REGISTRY=${ECR_REGISTRY}
          export ECR_REPOSITORY=${ECR_REPOSITORY}
          export GITHUB_SHA=${GITHUB_SHA}
          export POSTGRES_DB=${POSTGRES_DB}
          export POSTGRES_USER=${POSTGRES_USER}
          export POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          
          # Create SSL directory if it doesn't exist
          mkdir -p ~/ssl
          
          # Save SSL certificate and key
          echo "$SSL_CERT" > ~/ssl/fullchain.pem
          echo "$SSL_KEY" > ~/ssl/privkey.pem
          
          docker-compose pull
          docker-compose up -d
        EOF